name: week4

services:
  app:
    image: ica0022:v1.1.0
    build: .
    ports:
      - TODO_EXPOSE_PORTS
    environment: TODO_ADD_ENVS
    depends_on:
      db:
        condition: TODO_CONDITION
    networks: TODO_ADD_NETWORK

  db:
    image: postgres:17-bookworm
    environment: TODO_ADD_ENVS
    volumes:
      - TODO_BIND_VOLUME
      - TODO_BIND_MOUTN_PATH
    healthcheck: TODO_ADD_HEALTH_CHECK
    networks: TODO_ADD_NETWORK

networks: TODO_ADD_NETWORK

volumes: TODO_ADD_VOLUME